#!/usr/bin/env python3

import argparse
import sys
import os
import yaml

import coc
from coc.exceptions import *

from tui import interface,t
from tui.game_load import *

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-D', '--debug')
    parser.add_argument('-p', '--player', nargs=1, default=None)
# TODO: use os.fsencode() or something similar to make path name parsing os-agnostic
    parser.add_argument('-S', '--save-path', nargs=1, default='~/.coc/')
    parser.add_argument('--world-schema', nargs=1, default='classic/')
    args = parser.parse_args(sys.argv[1:])

    try:
        player_path = args.save_path + '/' + args.player
    except TypeError:
        try:
            player_path = select_player(os.path.expanduser(args.save_path))
        except ExitMenuException:
            sys.exit(0)

    session = coc.Session(world_path=args.world_schema, player_path=player_path, interface=interface)
